pyproject-nix/pyproject.nix

flake.nix

Hello,
Flake outputs are currently restricted to `x86_64-linux`, any objections to adding `aarch64` and darwin outputs? Test suite passes at least on `aarch64-darwin` as well.
Thank you so much for this! :)

Add additional systems to flake outputs

---

lib/pep508.nix

This way we're not assuming as much about the comparison operators and have much better support for comparing primitive types.
Closes https://github.com/adisbladis/pyproject.nix/pull/5

Add dynamic type lookups to evalMarkers

---

.github/workflows/nix-github-actions.yml

The most "magic" thing about it is how it turns your tail latency absolutely terrible and causes jobs to fail spuriously because of API rate limits.
Cachix probably gives us slightly worse performance in the common case but much better tail latency.

Migrate from the determinatesystems installer to cachix

---

templates/pyproject/flake.nix
templates/requirements-txt/flake.nix

In my environment, I get the following error when I attempt to run this Flake:
```text
error: function 'outputs' called with unexpected argument 'self'
at /nix/store/m8vmipjaw53ihc76vs40px1qm062plmy-source/flake.nix:11:5:
10|   outputs =
11|     { nixpkgs
|     ^
12|     , flake-utils
```
Adding `self` as an argument fixes the error.

Fix bug in requirements.txt template

---

lib/renderers.nix
lib/test_project.nix
lib/test_renderers.nix

Which is being added to nixpkgs in https://github.com/NixOS/nixpkgs/pull/339228
Closes #67 #114

renderers: Add mkPythonEditablePackage

---

build/hooks/make-venv.py

Give the user enough details to check out which file should be preferred, and suggest a way to do the overwrite (since it's not totally obvious).

fix: improve message on file collision

---

build/hooks/make-venv.py

The identical 'binary' detection was broken (tried to open the file in write mode, the offset used the wrong len(shebang)). Also extended the error message.
My test-case for this was 'llama-index', 
but that's not 'tiny', so I didn't implement it as a test case.

Fix write permission on duplicate binaries

---

build/hooks/make-venv.py

It's apparently a Python 3.12+ thing

build.make-venv: avoid using pathlib.Path("foo").exists with follow_symlinks

---

build/bootstrap.nix
build/pkgs/flit-core/default.nix

Fixes an issue where pyproject.nix cannot be used with recent nixos-unstable-small nixpkgs set because of differing definitions of flit-core.

update flit core to work with later nixpkgs

---

build/checks/build-systems.nix
build/checks/default.nix
build/hacks/checks.nix
build/lib/test_renderers.nix
build/packages.nix

Pyproject.nix's package set is being removed in favour of using https://github.com/pyproject-nix/build-system-pkgs which is automated.

build: Deprecate package set

---

build/hooks/default.nix
build/hooks/pyproject-install-hook.sh

And only use custom hook for cross where we can't yet use uv.

pyprojectInstallHook: Use uv's byte code compilation instead of custom hook

---

build/hooks/make-venv/make_venv.py

Tiny quality of life improvement. Had a package where there where 8 __init__.py files colliding, and this way you can copy/paste the filenames for a quick md5sum.
Now looks like
```
> __main__.FileCollisionError: Two or more packages are trying to provide the same file with different contents
>
>         Files: /nix/store/6qcjwvh8kx5bc10sbqkvsndjlqi3j2sw-azureml-core-1.57.0.post3/lib/python3.9/site-packages/azureml/__init__.py /nix/store/3dk98flclhm6fhpvz31bpsqrc4is7shz-azureml-train-automl-client-1.57.0/lib/python3.9/site-packages/azureml/__init__.py /nix/store/vvv01nh1v1s93z596pdwfhwsx7s1khrv-azureml-train-core-1.57.0/lib/python3.9/site-packages/azureml/__init__.py /nix/store/pnf0vb2a2gdsplsn77l8agqzz6mbki47-azureml-pipeline-core-1.57.0/lib/python3.9/site-packages/azureml/__init__.py …
```

fix: better collision error message (copy/pastable filenames)

---

build/default.nix
build/util/checks.nix
build/util/default.nix
build/util/mk-application.py
doc/src/SUMMARY.md
doc/src/build/util.md
flake.nix

This helper takes a virtual environment and a derivation to use as a structure template & outputs a derivation without venv cruft.
See https://github.com/pyproject-nix/uv2nix/issues/80
cc @jfly

build: Add util.mkApplication

---

build/lib/renderers.nix
doc/src/build.md
flake.nix

Uv builds being binary reproducible was the last blocker, and uv 0.5.7 which contains support for disabling non-reproducible metadata has now reached nixos-unstable-small.
`mkDerivationEditable` is still marked as unstable because I'm not sure about the final api.

build: Remove experimental label

---

build/lib/renderers.nix

As those are useful to refer to local packages relative to the root of a bigger repository. i.e.
```
optional-dependencies.foo = [
"foo @ file:///{root:uri}/sub/dir/foo",
]
```

build: allow direct references in metadata

---

build/lib/renderers.nix

By making it possible to override the synthetic `pyproject.toml`'s project table.
This makes it possible to manually pass fields such as version which may be dynamic.

build.lib.renderers: Improve dynamic metadata support

---

doc/src/HACKING.md
doc/src/build.md
doc/src/builders/hacks.md
doc/src/builders/overriding.md
doc/src/builders/packages.md
doc/src/nixpkgs-build.md

This corrects some typos in documentation, e.g., it's -> its; so -> to.

doc: Fix typo

---

build/checks/build-systems.nix
build/checks/default.nix
build/hooks/default.nix
build/hooks/editable_hook/default.nix
build/hooks/editable_hook/editable_hook/build_editable.py
build/hooks/editable_hook/editable_hook/patch_editable.py
build/hooks/editable_hook/fixtures/input.pth
build/hooks/editable_hook/fixtures/input.py
build/hooks/editable_hook/fixtures/output.pth
build/hooks/editable_hook/fixtures/output.py
build/hooks/editable_hook/pyproject.toml
build/hooks/editable_hook/shell.nix
build/hooks/editable_hook/test_patch_editable.py
build/hooks/pyproject-build-editable-hook.sh
build/hooks/pyproject-fixup-editable-hook.sh
build/lib/renderers.nix
build/lib/test_renderers.nix
build/packages.nix
pyproject.toml
treefmt.nix

The previously used mechanism of synthezising a package using hatchling sort of works, and was enough to prove the concept of editables with Nix.
This changes `mkDerivationEditable` to use PEP-660 and should support pretty much everything.
The big complication in this development was the need for source level patching since editables are a pretty loose concept and are implemented differently by different build systems. Source patching uses https://github.com/Instagram/LibCST/. I'd like to rewrite this bit purely in Rust later.
So far I've successfully used this support with a few build systems, most notably meson.
For meson this requires manually calling `build_editable.py` to create the initial files. After that point dynamic recompilation "just works". This will be exposed as a separate …

build: Rework editables for full PEP-660 support

---

build/checks/default.nix
build/hooks/make-venv/make_venv.py

The venv module creates a symlink to the Python interpreter, but this breaks the venv if you're using a symlink pointing to the virtualenv itself.
By replacing the Python interpreter symlink with a wrapper it can be properly linked to in another derivation.
cc @TyberiusPrime

build.hooks.make-venv: Replace symlink to Python interpreter with a binary wrapper

---

lib/pypa.nix

Problem: On Linux-aarch64 machines the `platform.linuxArch` contains `arm64` which is not the wheel suffix that is commonly used for Linux-aarch64 filenames (e.g., https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/ does not list `arm64` as part of a platform tag for Linux).
Solution: This change swaps out `arm64` with `aarch64` to find compatible wheels.

Translate arm64 to aarch64 for wheel names

---

build/checks/default.nix
build/hooks/default.nix
build/hooks/dist-hook/install-wheels.py
build/hooks/dist-hook/pyproject-install-dist-hook.sh
build/packages.nix

`pyprojectDistHook` is to be used instead of `pyprojectHook` when you want to get the wheel files instead of the installed files.

build.hooks: Add hook to install dist directory into output

---

build/lib/default.nix
build/lib/query.nix
build/lib/test.nix
build/lib/test_query.nix
doc/src/SUMMARY.md
doc/src/build/lib/query.md

This API is useful if you want to create a virtualenv consisting of a packages dependencies, but without the package itself.
``` nix
pythonSet.mkVirtualEnv "hello-env" {
hello-world = [ "dev" ];
}
```
will create a virtual environment with `hello-world` _and_ its development dependencies.
``` nix
pythonSet.mkVirtualEnv "hello-env" (query.deps { } pythonSet {
hello-world = [ "dev" ];
}
```
will create a virtual environment with `hello-world`'s main dependencies & its development dependencies, but not `hello-world` itself.
``` nix
pythonSet.mkVirtualEnv "hello-env" (query.deps { dependencies = false; } pythonSet {
hello-world = [ "dev" ];
}
```
will create a virtual environment with `hello-world`'s development dependencies _only_.

build.lib.query: init package set query API

---

lib/pypa.nix

Instead, `platform` holds `is32bit` and `isx86_32`.

pypa: platform doesn't hold is32Bit and isx86

---

lib/pep599.nix

manyLinuxTargetMachines needs to get enhanced for further architectures.
error:
```
error: attribute 'riscv64' missing
at /nix/store/nmf1ggxf77gzv7cw5h91d6l1wh4y6qyj-source/lib/pep600.nix:62:13:
61|     else if compareVersions "${sysMajor}.${sysMinor}" "${tagMajor}.${tagMinor}" < 0 then false
62|     else if pep599.manyLinuxTargetMachines.${tagArch} != platform.parsed.cpu.name then false
|             ^
63|     else true;
Error: Process completed with exit code 1.
```
pdm.lock:
```
[[package]]
name = "rpds-py"
version = "0.27.1"
requires_python = ">=3.9"
summary = "Python bindings to Rust's persistent data structures (rpds)"
groups = ["default"]
files = [
{file = "rpds_py-0.27.1-cp312-cp312-macosx_10_12_x86_64.whl", hash = "sha256:ae2775c1973e3c30316892737b91f9283f9908e3cc7625b9331271eaaed …
```

add manylinux riscv64
